name: Build all devices

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt install -y arm-linux-gnu aarch64-linux-gnu

    - name: Run build_test.sh
      run: .github/workflows/build_test.sh
